### ISSUE TITLE
Crear mensaje con descripción a los productos

### ISSUE THREAD

**Issue by RamsesMartinez** [DigimundoTesca/Dabba_users#1]
En la pantalla de compra del usuario, se necesita agregar un "modal" con la descripción de los productos para que el usuario sepa de que "trata" el producto.

**Comment by Itzli2000** [comment]
En que seccion?
Como se llama el archivo en el cual quieres el "modal" y que es "modal"

**Comment by RamsesMartinez** [comment]
"Arma tu dabba" es donde el usuario Compra ... ¿no?

**Comment by Itzli2000** [comment]
Si, en arma tu dabba

**Comment by Itzli2000** [comment]
Pero la información de lo que contendrá cada producto estará en la sección de 'menú' por eso no considere agregarla en la sección de arma tu dabba

**Comment by RamsesMartinez** [comment]
Pero es tediosa la navegación, la revisé con josué, necesitamos que ahi coloques información descriptiva para el usuario

**Comment by Itzli2000** [comment]
Ok, como me dijiste desde un principio yo solo sigo los diseños que me entregaron, se que la navegación no es la mejor

**Comment by RamsesMartinez** [comment]
Para eso es este hilo, para corregir esa navegación :smile: 
En cuanto haya cambios recuerda avisa para revisarlos.

**Comment by Itzli2000** [comment]
Para este issue, ¿Quieren que la descripción del producto este debajo de la imagen y del nombre?

**Comment by RamsesMartinez** [comment]
donde consideres pertinente, quiza sea un mensaje que aparece cada vez que pasas el raton encima.

**Comment by Itzli2000** [comment]
Puedes revisar como lo hice en la seccion de rotis de elige te daba porfa y var si asi esta bien o es de otra manera

**Comment by Itzli2000** [comment]
Agregadas las descripciones a los productos.

**Comment by RamsesMartinez** [comment]
Issue finalizado
