### ISSUE TITLE
Eliminar botones y cambiar imagenes en Escoge tu dabba

### ISSUE THREAD

**Issue by RamsesMartinez** [DigimundoTesca/Dabba_users#2]
**1. Eliminar Botones**
Hay que eliminar los botones "Paquete" y "Escoge" 
[pick.html](https://digimundotesca.github.io/Dabba_users/pick.html)
Toda la imagen de fondo del contenedor debe funcionar como un "boton gigante".

**2. Cambiar imágenes"**
Cambia la Hamburguesa y la Pizza de Fondo, no tienen nada que ver.

**Comment by Itzli2000** [comment]
Las imagenes contenidas en la pagina son demostrativas, necesito las imagenes finales para agregarlas.
Se que hay imagenes que no tienen nada que ver, al igual que en las secciones de escoge tu dabba; las imagenes de rotis, jugos, fruta, licuados, etc son demostrativas.

Si gustas agrego nuevas imagenes pero aun así necesitos las imagenes reales de los productos que se venderan en dabba para que la pagina sea fiel.

**Comment by RamsesMartinez** [comment]
Por ahora pon quizá rotis, si tienes algo que traiga más de un roti esa estaría bien para la parte de "Arma tu dabba"

**Comment by Itzli2000** [comment]
Cambios requeridos en este issue completados, cambios listos para revisión

**Comment by RamsesMartinez** [comment]
ya están en gh-pages?

**Comment by Itzli2000** [comment]
Si ya esta en gh-pages, que hereda su info directamente de master para reflejar los cambios lo mas pronto posible

**Comment by RamsesMartinez** [comment]
Ya lo revisé, sólo faltaría crear un efect "hover" cada vez que se pase el raton, para que sea notorio

**Comment by Itzli2000** [comment]
Agregado efecto de realce con sombras para hacer evidente la selección de uno u otro elemento

**Comment by Itzli2000** [comment]
Correcciones de estilo, issue completado

**Comment by RamsesMartinez** [comment]
Encontré otro problema, aun no lo puedo cerrar jaja
Cuando alejas el zoom, las imagenes no tienen la misma anchura, por lo que no se ve nada bonito en tablets :/ habria que cambiar eso y sería todo.

**Comment by Itzli2000** [comment]
Como cual zoom?
El zoom lo tengo bloqueado

**Comment by RamsesMartinez** [comment]
O sea en pantallas donde las columnas se hacen una sola.

**Comment by Itzli2000** [comment]
Solucionado....

**Comment by RamsesMartinez** [comment]
Aún no, las sombras resaltan mucho y los tiempos de entrada son diferentes al tiempo de  salida del efecto.
Para que te des una idea de como se ve "bien" el efecto, fijate en este contenedor de mensajes, se nota que está seleccionado pero no está saturado de sombra.

**Comment by Itzli2000** [comment]
Si, asi elegi el efecto de las sombras, querias que fuera notorio cuando se seleccionara un div, y asi se ve claramente que esta seleccionado

**Comment by Itzli2000** [comment]
Agamos algo, para no estarte adivinando el pensamiento, mejor dime especificamente que es lo que quieres. Porque me das una indicación, la hago y despues quieres otra cosa y solo estamos perdiendo tiempo

**Comment by Itzli2000** [comment]
Ya le agregue el efecto de salida a las sombras y disminuí su tamaño

**Comment by RamsesMartinez** [comment]
Sólo hay que remover el efecto 3D sólo que haya un resplandor, ya que en la página no tienes elementos "flotantes" por lo tanto no es necesario.
Una vez eso ya pedo cerrar este issue :)

**Comment by Itzli2000** [comment]
Listo este cambio

**Comment by Itzli2000** [comment]
Ready!!!!!! Agregado box shadow con animación de entrada y salida

**Comment by RamsesMartinez** [comment]
Issue cerrado
