### ISSUE TITLE
Reparar Las rejillas del header

### ISSUE THREAD

**Issue by RamsesMartinez** [DigimundoTesca/Dabba_users#3]
Al llegar un tamaño de pantalla grande, el header nav no tiene simetria con el contenido del cuerpo de la pagina ni con el contenido del footer.

**Comment by Itzli2000** [comment]
¿Podrías ser mas específico en el error?
¿Que tamaño de pantalla causa problemas?

**Comment by RamsesMartinez** [comment]
Probablemente sea mayor de 1200px
Revisalo bien, porque no se autoajusta correctamente, cada uno se ven de diferentes anchuras

**Comment by Itzli2000** [comment]
Si, tengo ajustes del nav para resoluciones desde 1200px hacia abajo

**Comment by RamsesMartinez** [comment]
para abajo? revisa para pantallas superiores a esa resolucion, has un zoom out para que lo revises

**Comment by Itzli2000** [comment]
Si lo revisare

**Comment by Itzli2000** [comment]
Reparado comportamiento para header para pantallas desde 2000 px hasta 300 px

**Comment by RamsesMartinez** [comment]
desde 2000px? ... Lo correcto es decir desde pantallas de 300px hasta resoluciones mayores a 1200px o 1024px, etc...

**Comment by RamsesMartinez** [comment]
Falta qe revises el footer, se ve por decirlo a un 50% cuando el header y el container se ven aprox a un 75%

**Comment by Itzli2000** [comment]
Estas seguro que son issues reales?
Me suena raro

**Comment by Itzli2000** [comment]
Header y footer arreglados para diferentes tamaños de pantalla, lo puedes revisar porfa

**Comment by RamsesMartinez** [comment]
Este issue esta listo
